name = "sma-data-pwa"
main = "src/index.ts"

# Align with latest deploy date
compatibility_date = "2025-12-27"

# Static Assets
[assets]
directory = "./public"

[env.production]
vars = { ENVIRONMENT = "production" }
